"""Add Neuri models

Revision ID: edae03363bf4
Revises: b18dab14b282
Create Date: 2025-10-25 10:29:22.811303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'edae03363bf4'
down_revision: Union[str, None] = 'b18dab14b282'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('pace', sa.String(length=50), nullable=True),
    sa.Column('preferred_work_time', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('categories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_categories_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    op.create_index('ix_categories_created_at', 'categories', ['created_at'], unique=False)
    op.create_index(op.f('ix_categories_user_id'), 'categories', ['user_id'], unique=False)
    op.create_table('rewards',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.Column('total_tasks_done', sa.Integer(), nullable=False),
    sa.Column('milestones_unlocked', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_rewards_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rewards'))
    )
    op.create_index('ix_rewards_created_at', 'rewards', ['created_at'], unique=False)
    op.create_index(op.f('ix_rewards_user_id'), 'rewards', ['user_id'], unique=True)
    op.create_table('routines',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('schedule', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_routines_category_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_routines_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routines'))
    )
    op.create_index(op.f('ix_routines_category_id'), 'routines', ['category_id'], unique=False)
    op.create_index('ix_routines_created_at', 'routines', ['created_at'], unique=False)
    op.create_index(op.f('ix_routines_user_id'), 'routines', ['user_id'], unique=False)
    op.create_table('missions',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('TASK', 'PROJECT', 'NOTE', 'REMINDER', name='missiontype'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('parent_project_id', sa.Uuid(), nullable=True),
    sa.Column('parent_routine_id', sa.Uuid(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('true_deadline', sa.DateTime(), nullable=True),
    sa.Column('personal_deadline', sa.DateTime(), nullable=True),
    sa.Column('recurrence_rule', sa.String(length=100), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('heaviness', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_missions_category_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_project_id'], ['missions.id'], name=op.f('fk_missions_parent_project_id_missions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_routine_id'], ['routines.id'], name=op.f('fk_missions_parent_routine_id_routines'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_missions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_missions'))
    )
    op.create_index(op.f('ix_missions_category_id'), 'missions', ['category_id'], unique=False)
    op.create_index('ix_missions_created_at', 'missions', ['created_at'], unique=False)
    op.create_index(op.f('ix_missions_parent_project_id'), 'missions', ['parent_project_id'], unique=False)
    op.create_index(op.f('ix_missions_parent_routine_id'), 'missions', ['parent_routine_id'], unique=False)
    op.create_index(op.f('ix_missions_user_id'), 'missions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_missions_user_id'), table_name='missions')
    op.drop_index(op.f('ix_missions_parent_routine_id'), table_name='missions')
    op.drop_index(op.f('ix_missions_parent_project_id'), table_name='missions')
    op.drop_index('ix_missions_created_at', table_name='missions')
    op.drop_index(op.f('ix_missions_category_id'), table_name='missions')
    op.drop_table('missions')
    op.drop_index(op.f('ix_routines_user_id'), table_name='routines')
    op.drop_index('ix_routines_created_at', table_name='routines')
    op.drop_index(op.f('ix_routines_category_id'), table_name='routines')
    op.drop_table('routines')
    op.drop_index(op.f('ix_rewards_user_id'), table_name='rewards')
    op.drop_index('ix_rewards_created_at', table_name='rewards')
    op.drop_table('rewards')
    op.drop_index(op.f('ix_categories_user_id'), table_name='categories')
    op.drop_index('ix_categories_created_at', table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('ix_users_created_at', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
